### ISSUE TITLE
The Language Server server crashes on very large files

### ISSUE THREAD

**Issue by xoxloviwan** [intersystems/language-server#174]
When I open big file *.cls ~1.75 MB
```
[Info  - 10:50:18] Connection to server got closed. Server will restart.
[Error - 10:50:18] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\xoxlo\.vscode\extensions\intersystems.language-server-1.2.2\client\node_modules\vscode-jsonrpc\lib\common\connection.js:1061:27)
	at Object.dispose (c:\Users\xoxlo\.vscode\extensions\intersystems.language-server-1.2.2\client\node_modules\vscode-languageclient\lib\common\client.js:73:35)
	at LanguageClient.handleConnectionClosed (c:\Users\xoxlo\.vscode\extensions\intersystems.language-server-1.2.2\client\node_modules\vscode-languageclient\lib\common\client.js:2474:42)
	at LanguageClient.handleConnectionClosed (c:\Users\xoxlo\.vscode\extensions\intersystems.language-server-1.2.2\client\node_modules\vscode-languageclient\lib\node\main.js:159:15)
	at closeHandler (c:\Users\xoxlo\.vscode\extensions\intersystems.language-server-1.2.2\client\node_modules\vscode-languageclient\lib\common\client.js:2461:18)
	at CallbackList.invoke (c:\Users\xoxlo\.vscode\extensions\intersystems.language-server-1.2.2\client\node_modules\vscode-jsonrpc\lib\common\events.js:55:39)
	at Emitter.fire (c:\Users\xoxlo\.vscode\extensions\intersystems.language-server-1.2.2\client\node_modules\vscode-jsonrpc\lib\common\events.js:117:36)
	at closeHandler (c:\Users\xoxlo\.vscode\extensions\intersystems.language-server-1.2.2\client\node_modules\vscode-jsonrpc\lib\common\connection.js:260:26)
	at CallbackList.invoke (c:\Users\xoxlo\.vscode\extensions\intersystems.language-server-1.2.2\client\node_modules\vscode-jsonrpc\lib\common\events.js:55:39)
	at Emitter.fire (c:\Users\xoxlo\.vscode\extensions\intersystems.language-server-1.2.2\client\node_modules\vscode-jsonrpc\lib\common\events.js:117:36)
	at IPCMessageReader.fireClose (c:\Users\xoxlo\.vscode\extensions\intersystems.language-server-1.2.2\client\node_modules\vscode-jsonrpc\lib\common\messageReader.js:40:27)
	at ChildProcess.<anonymous> (c:\Users\xoxlo\.vscode\extensions\intersystems.language-server-1.2.2\client\node_modules\vscode-jsonrpc\lib\node\main.js:33:45)
	at ChildProcess.emit (events.js:327:22)
	at maybeClose (internal/child_process.js:1048:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
[Error - 10:50:18] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\xoxlo\.vscode\extensions\intersystems.language-server-1.2.2\client\node_modules\vscode-jsonrpc\lib\common\connection.js:1061:27)
	at Object.dispose (c:\Users\xoxlo\.vscode\extensions\intersystems.language-server-1.2.2\client\node_modules\vscode-languageclient\lib\common\client.js:73:35)
	at LanguageClient.handleConnectionClosed (c:\Users\xoxlo\.vscode\extensions\intersystems.language-server-1.2.2\client\node_modules\vscode-languageclient\lib\common\client.js:2474:42)
	at LanguageClient.handleConnectionClosed (c:\Users\xoxlo\.vscode\extensions\intersystems.language-server-1.2.2\client\node_modules\vscode-languageclient\lib\node\main.js:159:15)
	at closeHandler (c:\Users\xoxlo\.vscode\extensions\intersystems.language-server-1.2.2\client\node_modules\vscode-languageclient\lib\common\client.js:2461:18)
	at CallbackList.invoke (c:\Users\xoxlo\.vscode\extensions\intersystems.language-server-1.2.2\client\node_modules\vscode-jsonrpc\lib\common\events.js:55:39)
	at Emitter.fire (c:\Users\xoxlo\.vscode\extensions\intersystems.language-server-1.2.2\client\node_modules\vscode-jsonrpc\lib\common\events.js:117:36)
	at closeHandler (c:\Users\xoxlo\.vscode\extensions\intersystems.language-server-1.2.2\client\node_modules\vscode-jsonrpc\lib\common\connection.js:260:26)
	at CallbackList.invoke (c:\Users\xoxlo\.vscode\extensions\intersystems.language-server-1.2.2\client\node_modules\vscode-jsonrpc\lib\common\events.js:55:39)
	at Emitter.fire (c:\Users\xoxlo\.vscode\extensions\intersystems.language-server-1.2.2\client\node_modules\vscode-jsonrpc\lib\common\events.js:117:36)
	at IPCMessageReader.fireClose (c:\Users\xoxlo\.vscode\extensions\intersystems.language-server-1.2.2\client\node_modules\vscode-jsonrpc\lib\common\messageReader.js:40:27)
	at ChildProcess.<anonymous> (c:\Users\xoxlo\.vscode\extensions\intersystems.language-server-1.2.2\client\node_modules\vscode-jsonrpc\lib\node\main.js:33:45)
	at ChildProcess.emit (events.js:327:22)
	at maybeClose (internal/child_process.js:1048:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
[Error - 10:50:18] Request textDocument/semanticTokens/full failed.
Error: Connection got disposed.
```
Then
The InterSystems Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

Version: 1.57.1 (user setup)
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:07.755Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042
InterSystems Language Server: 1.2.2
InterSystems Language Server version without error: 1.1.4

**Comment by isc-bsaviano** [comment]
@xoxloviwan How many lines is your file? The fix for #164 was verified with a MAC routine that was about 24000 lines long and 1.5MB in size. Parsing a file near that length is very slow but won't crash.

**Comment by xoxloviwan** [comment]
> @xoxloviwan How many lines is your file? The fix for #164 was verified with a MAC routine that was about 24000 lines long and 1.5MB in size. Parsing a file near that length is very slow but won't crash.

~19815 lines
In our prod there is also legacy CLS file with 35478 lines (~3,2 MB) that language server made crashed.

**Comment by isc-bsaviano** [comment]
@xoxloviwan Yeah, those files are just too large. If we increase the memory any further so we don't crash the parsing will take so long that it's not worth the effort. I can consider adding a check that will prevent the LS from crashing on these large files but you won't get intellisense for them.

**Comment by xoxloviwan** [comment]
But why this files not made server crashed in version 1.1.4 + VSCode 1.54.3 (user setup) ?

I cannot detect this problem for this build:
Version: 1.54.3 (user setup)
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T10:55:45.459Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042
InterSystems Language Server: 1.1.4

**Comment by xoxloviwan** [comment]
When I update VS Code from 1.54.3 to 1.57.1 (InterSystems Language Server: 1.1.4) I got this:

```

#
# Fatal error in , line 0
# ignored
#
#
#
#FailureMessage Object: 0000007ABA7FC4D0
 1: 00007FF60786656F node::OnFatalError+70575
 2: 00007FF6086B982A v8::FunctionTemplate::RemovePrototype+593498
 3: 00007FF6066F116A v8::ArrayBuffer::GetBackingStore+922
 4: 00007FF6066F0E2F v8::ArrayBuffer::GetBackingStore+95
 5: 00007FF607AFE899 napi_get_typedarray_info+425
 6: 00007FFA19A16FC1 
 7: 00007FFA19A1350F 
 8: 00007FFA19A1730E 
 9: 00007FFA19A17467 
10: 00007FFA19A172B3 
11: 00007FF607B003BA napi_is_detached_arraybuffer+330
12: 00007FF60816F061 v8::Object::SetLazyDataProperty+479745
13: 00007FF60816EAAC v8::Object::SetLazyDataProperty+478284
14: 00007FF60816E81B v8::Object::SetLazyDataProperty+477627
15: 00007FF60816E6D7 v8::Object::SetLazyDataProperty+477303
16: 00007FF6076434FC v8_inspector::protocol::Binary::operator=+455196
17: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
18: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
19: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
20: 00007FF6075DA63B v8_inspector::protocol::Binary::operator=+25435
21: 00007FF6075DA28C v8_inspector::protocol::Binary::operator=+24492
22: 00007FF607EB6904 Cr_z_deflate+100052
23: 00007FF607EB4A92 Cr_z_deflate+92258
24: 00007FF607EB44FB Cr_z_deflate+90827
25: 00007FF607EB1807 Cr_z_deflate+79319
26: 00007FF6081FA508 v8::Value::IsInt32+324248
27: 00007FF6081F9FF7 v8::Value::IsInt32+322951
28: 00007FF6076433FC v8_inspector::protocol::Binary::operator=+454940
29: 00007FF6076C7A56 v8_inspector::protocol::Binary::operator=+997238
30: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
31: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
32: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
33: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
34: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
35: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
36: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
37: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
38: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
39: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
40: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
41: 00007FF6075DA63B v8_inspector::protocol::Binary::operator=+25435
42: 00007FF6075DA28C v8_inspector::protocol::Binary::operator=+24492
43: 00007FF607EB6904 Cr_z_deflate+100052
44: 00007FF607EB4A92 Cr_z_deflate+92258
45: 00007FF607F74B0D v8::Function::Call+365
46: 00007FF6078081D7 node::CallbackScope::CallbackScope+2423
47: 00007FF607808589 node::MakeCallback+249
48: 00007FF60783CEC0 node::EmitAsyncDestroy+198128
49: 00007FF607943A66 uv_check_stop+150
50: 00007FF6078704D3 uv_run+1267
51: 00007FF60743EEE1 v8_inspector::protocol::Binary::~Binary+139553
52: 00007FF6072C3CCB GetHandleVerifier+4064027
53: 00007FF60867AAA2 v8::FunctionTemplate::RemovePrototype+336082
54: 00007FFA24BC7034 BaseThreadInitThunk+20
55: 00007FFA25022651 RtlUserThreadStart+33
[Info  - 22:20:23] Connection to server got closed. Server will restart.


#
# Fatal error in , line 0
# ignored
#
#
#
#FailureMessage Object: 000000892F7FC270
 1: 00007FF60786656F node::OnFatalError+70575
 2: 00007FF6086B982A v8::FunctionTemplate::RemovePrototype+593498
 3: 00007FF6066F116A v8::ArrayBuffer::GetBackingStore+922
 4: 00007FF6066F0E2F v8::ArrayBuffer::GetBackingStore+95
 5: 00007FF607AFE899 napi_get_typedarray_info+425
 6: 00007FFA19A16FC1 
 7: 00007FFA19A1350F 
 8: 00007FFA19A1730E 
 9: 00007FFA19A17467 
10: 00007FFA19A172B3 
11: 00007FF607B003BA napi_is_detached_arraybuffer+330
12: 00007FF60816F061 v8::Object::SetLazyDataProperty+479745
13: 00007FF60816EAAC v8::Object::SetLazyDataProperty+478284
14: 00007FF60816E81B v8::Object::SetLazyDataProperty+477627
15: 00007FF60816E6D7 v8::Object::SetLazyDataProperty+477303
16: 00007FF6076434FC v8_inspector::protocol::Binary::operator=+455196
17: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
18: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
19: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
20: 00007FF6075DA63B v8_inspector::protocol::Binary::operator=+25435
21: 00007FF6075DA28C v8_inspector::protocol::Binary::operator=+24492
22: 00007FF607EB6904 Cr_z_deflate+100052
23: 00007FF607EB4A92 Cr_z_deflate+92258
24: 00007FF607EB44FB Cr_z_deflate+90827
25: 00007FF607EB1807 Cr_z_deflate+79319
26: 00007FF6081FA508 v8::Value::IsInt32+324248
27: 00007FF6081F9FF7 v8::Value::IsInt32+322951
28: 00007FF6076433FC v8_inspector::protocol::Binary::operator=+454940
29: 00007FF6076C7A56 v8_inspector::protocol::Binary::operator=+997238
30: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
31: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
32: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
33: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
34: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
35: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
36: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
37: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
38: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
39: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
40: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
41: 00007FF6075DA63B v8_inspector::protocol::Binary::operator=+25435
42: 00007FF6075DA28C v8_inspector::protocol::Binary::operator=+24492
43: 00007FF607EB6904 Cr_z_deflate+100052
44: 00007FF607EB4A92 Cr_z_deflate+92258
45: 00007FF607F74B0D v8::Function::Call+365
46: 00007FF6078081D7 node::CallbackScope::CallbackScope+2423
47: 00007FF607808589 node::MakeCallback+249
48: 00007FF60783CEC0 node::EmitAsyncDestroy+198128
49: 00007FF607943A66 uv_check_stop+150
50: 00007FF6078704D3 uv_run+1267
51: 00007FF60743EEE1 v8_inspector::protocol::Binary::~Binary+139553
52: 00007FF6072C3CCB GetHandleVerifier+4064027
53: 00007FF60867AAA2 v8::FunctionTemplate::RemovePrototype+336082
54: 00007FFA24BC7034 BaseThreadInitThunk+20
55: 00007FFA25022651 RtlUserThreadStart+33
[Info  - 22:20:25] Connection to server got closed. Server will restart.


#
# Fatal error in , line 0
# ignored
#
#
#
#FailureMessage Object: 0000006890FFC330
 1: 00007FF60786656F node::OnFatalError+70575
 2: 00007FF6086B982A v8::FunctionTemplate::RemovePrototype+593498
 3: 00007FF6066F116A v8::ArrayBuffer::GetBackingStore+922
 4: 00007FF6066F0E2F v8::ArrayBuffer::GetBackingStore+95
 5: 00007FF607AFE899 napi_get_typedarray_info+425
 6: 00007FFA12736FC1 
 7: 00007FFA1273350F 
 8: 00007FFA1273730E 
 9: 00007FFA12737467 
10: 00007FFA127372B3 
11: 00007FF607B003BA napi_is_detached_arraybuffer+330
12: 00007FF60816F061 v8::Object::SetLazyDataProperty+479745
13: 00007FF60816EAAC v8::Object::SetLazyDataProperty+478284
14: 00007FF60816E81B v8::Object::SetLazyDataProperty+477627
15: 00007FF60816E6D7 v8::Object::SetLazyDataProperty+477303
16: 00007FF6076434FC v8_inspector::protocol::Binary::operator=+455196
17: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
18: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
19: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
20: 00007FF6075DA63B v8_inspector::protocol::Binary::operator=+25435
21: 00007FF6075DA28C v8_inspector::protocol::Binary::operator=+24492
22: 00007FF607EB6904 Cr_z_deflate+100052
23: 00007FF607EB4A92 Cr_z_deflate+92258
24: 00007FF607EB44FB Cr_z_deflate+90827
25: 00007FF607EB1807 Cr_z_deflate+79319
26: 00007FF6081FA508 v8::Value::IsInt32+324248
27: 00007FF6081F9FF7 v8::Value::IsInt32+322951
28: 00007FF6076433FC v8_inspector::protocol::Binary::operator=+454940
29: 00007FF6076C7A56 v8_inspector::protocol::Binary::operator=+997238
30: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
31: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
32: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
33: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
34: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
35: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
36: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
37: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
38: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
39: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
40: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
41: 00007FF6075DA63B v8_inspector::protocol::Binary::operator=+25435
42: 00007FF6075DA28C v8_inspector::protocol::Binary::operator=+24492
43: 00007FF607EB6904 Cr_z_deflate+100052
44: 00007FF607EB4A92 Cr_z_deflate+92258
45: 00007FF607F74B0D v8::Function::Call+365
46: 00007FF6078081D7 node::CallbackScope::CallbackScope+2423
47: 00007FF607808589 node::MakeCallback+249
48: 00007FF60783CEC0 node::EmitAsyncDestroy+198128
49: 00007FF607943A66 uv_check_stop+150
50: 00007FF6078704D3 uv_run+1267
51: 00007FF60743EEE1 v8_inspector::protocol::Binary::~Binary+139553
52: 00007FF6072C3CCB GetHandleVerifier+4064027
53: 00007FF60867AAA2 v8::FunctionTemplate::RemovePrototype+336082
54: 00007FFA24BC7034 BaseThreadInitThunk+20
55: 00007FFA25022651 RtlUserThreadStart+33
[Info  - 22:20:28] Connection to server got closed. Server will restart.


#
# Fatal error in , line 0
# ignored
#
#
#
#FailureMessage Object: 00000022211FC480
 1: 00007FF60786656F node::OnFatalError+70575
 2: 00007FF6086B982A v8::FunctionTemplate::RemovePrototype+593498
 3: 00007FF6066F116A v8::ArrayBuffer::GetBackingStore+922
 4: 00007FF6066F0E2F v8::ArrayBuffer::GetBackingStore+95
 5: 00007FF607AFE899 napi_get_typedarray_info+425
 6: 00007FFA12736FC1 
 7: 00007FFA1273350F 
 8: 00007FFA1273730E 
 9: 00007FFA12737467 
10: 00007FFA127372B3 
11: 00007FF607B003BA napi_is_detached_arraybuffer+330
12: 00007FF60816F061 v8::Object::SetLazyDataProperty+479745
13: 00007FF60816EAAC v8::Object::SetLazyDataProperty+478284
14: 00007FF60816E81B v8::Object::SetLazyDataProperty+477627
15: 00007FF60816E6D7 v8::Object::SetLazyDataProperty+477303
16: 00007FF6076434FC v8_inspector::protocol::Binary::operator=+455196
17: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
18: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
19: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
20: 00007FF6075DA63B v8_inspector::protocol::Binary::operator=+25435
21: 00007FF6075DA28C v8_inspector::protocol::Binary::operator=+24492
22: 00007FF607EB6904 Cr_z_deflate+100052
23: 00007FF607EB4A92 Cr_z_deflate+92258
24: 00007FF607EB44FB Cr_z_deflate+90827
25: 00007FF607EB1807 Cr_z_deflate+79319
26: 00007FF6081FA508 v8::Value::IsInt32+324248
27: 00007FF6081F9FF7 v8::Value::IsInt32+322951
28: 00007FF6076433FC v8_inspector::protocol::Binary::operator=+454940
29: 00007FF6076C7A56 v8_inspector::protocol::Binary::operator=+997238
30: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
31: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
32: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
33: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
34: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
35: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
36: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
37: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
38: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
39: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
40: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
41: 00007FF6075DA63B v8_inspector::protocol::Binary::operator=+25435
42: 00007FF6075DA28C v8_inspector::protocol::Binary::operator=+24492
43: 00007FF607EB6904 Cr_z_deflate+100052
44: 00007FF607EB4A92 Cr_z_deflate+92258
45: 00007FF607F74B0D v8::Function::Call+365
46: 00007FF6078081D7 node::CallbackScope::CallbackScope+2423
47: 00007FF607808589 node::MakeCallback+249
48: 00007FF60783CEC0 node::EmitAsyncDestroy+198128
49: 00007FF607943A66 uv_check_stop+150
50: 00007FF6078704D3 uv_run+1267
51: 00007FF60743EEE1 v8_inspector::protocol::Binary::~Binary+139553
52: 00007FF6072C3CCB GetHandleVerifier+4064027
53: 00007FF60867AAA2 v8::FunctionTemplate::RemovePrototype+336082
54: 00007FFA24BC7034 BaseThreadInitThunk+20
55: 00007FFA25022651 RtlUserThreadStart+33
[Info  - 22:20:30] Connection to server got closed. Server will restart.


#
# Fatal error in , line 0
# ignored
#
#
#
#FailureMessage Object: 00000039CDFFC060
 1: 00007FF60786656F node::OnFatalError+70575
 2: 00007FF6086B982A v8::FunctionTemplate::RemovePrototype+593498
 3: 00007FF6066F116A v8::ArrayBuffer::GetBackingStore+922
 4: 00007FF6066F0E2F v8::ArrayBuffer::GetBackingStore+95
 5: 00007FF607AFE899 napi_get_typedarray_info+425
 6: 00007FFA12736FC1 
 7: 00007FFA1273350F 
 8: 00007FFA1273730E 
 9: 00007FFA12737467 
10: 00007FFA127372B3 
11: 00007FF607B003BA napi_is_detached_arraybuffer+330
12: 00007FF60816F061 v8::Object::SetLazyDataProperty+479745
13: 00007FF60816EAAC v8::Object::SetLazyDataProperty+478284
14: 00007FF60816E81B v8::Object::SetLazyDataProperty+477627
15: 00007FF60816E6D7 v8::Object::SetLazyDataProperty+477303
16: 00007FF6076434FC v8_inspector::protocol::Binary::operator=+455196
17: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
18: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
19: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
20: 00007FF6075DA63B v8_inspector::protocol::Binary::operator=+25435
21: 00007FF6075DA28C v8_inspector::protocol::Binary::operator=+24492
22: 00007FF607EB6904 Cr_z_deflate+100052
23: 00007FF607EB4A92 Cr_z_deflate+92258
24: 00007FF607EB44FB Cr_z_deflate+90827
25: 00007FF607EB1807 Cr_z_deflate+79319
26: 00007FF6081FA508 v8::Value::IsInt32+324248
27: 00007FF6081F9FF7 v8::Value::IsInt32+322951
28: 00007FF6076433FC v8_inspector::protocol::Binary::operator=+454940
29: 00007FF6076C7A56 v8_inspector::protocol::Binary::operator=+997238
30: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
31: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
32: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
33: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
34: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
35: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
36: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
37: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
38: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
39: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
40: 00007FF6075DC9EF v8_inspector::protocol::Binary::operator=+34575
41: 00007FF6075DA63B v8_inspector::protocol::Binary::operator=+25435
42: 00007FF6075DA28C v8_inspector::protocol::Binary::operator=+24492
43: 00007FF607EB6904 Cr_z_deflate+100052
44: 00007FF607EB4A92 Cr_z_deflate+92258
45: 00007FF607F74B0D v8::Function::Call+365
46: 00007FF6078081D7 node::CallbackScope::CallbackScope+2423
47: 00007FF607808589 node::MakeCallback+249
48: 00007FF60783CEC0 node::EmitAsyncDestroy+198128
49: 00007FF607943A66 uv_check_stop+150
50: 00007FF6078704D3 uv_run+1267
51: 00007FF60743EEE1 v8_inspector::protocol::Binary::~Binary+139553
52: 00007FF6072C3CCB GetHandleVerifier+4064027
53: 00007FF60867AAA2 v8::FunctionTemplate::RemovePrototype+336082
54: 00007FFA24BC7034 BaseThreadInitThunk+20
55: 00007FFA25022651 RtlUserThreadStart+33
[Error - 22:20:32] Connection to server got closed. Server will not be restarted.

```

**Comment by xoxloviwan** [comment]
Analogically I got error stack as in first message when setup VS Code 1.54.3 and update InterSystems Language Server from 1.1.4 to 1.1.5

**Comment by isc-bsaviano** [comment]
@xoxloviwan See #152. In short, VS Code updated their node version, which broke some of our dependencies so we had to change them.

**Comment by xoxloviwan** [comment]
What will be impact more on intellisense difficulty? Number of labels, number of lines, line length, numbers of defined expressions?
Is it possible to parse not all file, for example only some thousand before and some thousand after cursor?

> @xoxloviwan Yeah, those files are just too large. If we increase the memory any further so we don't crash the parsing will take so long that it's not worth the effort. I can consider adding a check that will prevent the LS from crashing on these large files but you won't get intellisense for them.

If it is possible only that as @isc-bsaviano proposed it will be already better

**Comment by UmkaBearpaw** [comment]
> @xoxloviwan Yeah, those files are just too large. If we increase the memory any further so we don't crash the parsing will take so long that it's not worth the effort. I can consider adding a check that will prevent the LS from crashing on these large files but you won't get intellisense for them.

Hi, got the same problem with huge legacy class. There is no way to split into several classes right now. Is it possible to implement the proposed check?

**Comment by isc-bsaviano** [comment]
I did some research and I haven't figured out a way to exclude files based on length. The [DocumentSelector](https://code.visualstudio.com/api/references/document-selector) that the LS uses doesn't give that as an option. @gjsjohnmurray do you have any ideas?

**Comment by gjsjohnmurray** [comment]
@isc-bsaviano can LS call vscode.workspace.fs.stat to discover the size of a file the first time it is asked to process it? However I haven't verified if the isfs FSP returns a true size (or at least an accurate enough one for the purpose of deciding "too big to parse").

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray I would have to do that in the middleware on the client side since the LS itself doesn't have access to the `vscode` apis. I think I would be required to intercept every request to the server to do that check, which doesn't seem like a good way to do this.

**Comment by random343** [comment]
Hello.
I also have the same problem with large files.
I really need a solution to the problem.

**Comment by AlexeyM64** [comment]
Hello,
I've got the similar problem with huge classes. The proposed check sounds reasonable as it's better than nothing. Implement it, please!

**Comment by isc-bsaviano** [comment]
@xoxloviwan @random343 @UmkaBearpaw @AlexeyM64 Can you download Language Server version 2.0.0 and check if this problem still occurs?

**Comment by UmkaBearpaw** [comment]
> Can you download Language Server version 2.0.0 and check if this problem still occurs?

Hello. How can I download and install this version for my VSCode? Have you any instruction?

**Comment by gjsjohnmurray** [comment]
@UmkaBearpaw 2.0.0 is already published on Marketplace. Go to the Extensions view in VS Code and look at the LS entry there. If it doesn't already offer you an update, click the "..." menu at the top right corner of the panel to get an option to check for updates.

**Comment by UmkaBearpaw** [comment]
Yes, thank you. Update LanguageServer to 2.0.0 is really solve this problem, error is not occur while open big class. Thank you very much.

**Comment by xoxloviwan** [comment]
Error message not appear, thank you
Is it normal that LanguageServer extension log on tab Output disappeared ?

**Comment by isc-bsaviano** [comment]
@xoxloviwan Yes, by default the Language Server produces no output. You can change that using the `"intersystems.language-server.trace.server"` setting. See https://intersystems-community.github.io/vscode-objectscript/settings/#language-server
