### ISSUE TITLE
Failed in GitHub Codespaces 

### ISSUE THREAD

**Issue by daimor** [intersystems/language-server#185]
When running some environment with GitHub Codespaces, the extension fails there
```
node: malloc.c:2401: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
[Info  - 8:19:00 AM] Connection to server got closed. Server will restart.
[Error - 8:19:00 AM] Request textDocument/codeAction failed.
Error: Connection got disposed.
    at Object.dispose (/home/irisowner/.vscode-remote/extensions/intersystems.language-server-1.2.2/client/node_modules/vscode-jsonrpc/lib/common/connection.js:1061:27)
    at Object.dispose (/home/irisowner/.vscode-remote/extensions/intersystems.language-server-1.2.2/client/node_modules/vscode-languageclient/lib/common/client.js:73:35)
    at LanguageClient.handleConnectionClosed (/home/irisowner/.vscode-remote/extensions/intersystems.language-server-1.2.2/client/node_modules/vscode-languageclient/lib/common/client.js:2474:42)
    at LanguageClient.handleConnectionClosed (/home/irisowner/.vscode-remote/extensions/intersystems.language-server-1.2.2/client/node_modules/vscode-languageclient/lib/node/main.js:159:15)
    at closeHandler (/home/irisowner/.vscode-remote/extensions/intersystems.language-server-1.2.2/client/node_modules/vscode-languageclient/lib/common/client.js:2461:18)
    at CallbackList.invoke (/home/irisowner/.vscode-remote/extensions/intersystems.language-server-1.2.2/client/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
    at Emitter.fire (/home/irisowner/.vscode-remote/extensions/intersystems.language-server-1.2.2/client/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
    at closeHandler (/home/irisowner/.vscode-remote/extensions/intersystems.language-server-1.2.2/client/node_modules/vscode-jsonrpc/lib/common/connection.js:260:26)
    at CallbackList.invoke (/home/irisowner/.vscode-remote/extensions/intersystems.language-server-1.2.2/client/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
    at Emitter.fire (/home/irisowner/.vscode-remote/extensions/intersystems.language-server-1.2.2/client/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
    at IPCMessageReader.fireClose (/home/irisowner/.vscode-remote/extensions/intersystems.language-server-1.2.2/client/node_modules/vscode-jsonrpc/lib/common/messageReader.js:40:27)
    at ChildProcess.<anonymous> (/home/irisowner/.vscode-remote/extensions/intersystems.language-server-1.2.2/client/node_modules/vscode-jsonrpc/lib/node/main.js:33:45)
    at ChildProcess.emit (events.js:327:22)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:673:12)
[Error - 8:19:00 AM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
    at Object.dispose (/home/irisowner/.vscode-remote/extensions/intersystems.language-server-1.2.2/client/node_modules/vscode-jsonrpc/lib/common/connection.js:1061:27)
    at Object.dispose (/home/irisowner/.vscode-remote/extensions/intersystems.language-server-1.2.2/client/node_modules/vscode-languageclient/lib/common/client.js:73:35)
    at LanguageClient.handleConnectionClosed (/home/irisowner/.vscode-remote/extensions/intersystems.language-server-1.2.2/client/node_modules/vscode-languageclient/lib/common/client.js:2474:42)
    at LanguageClient.handleConnectionClosed (/home/irisowner/.vscode-remote/extensions/intersystems.language-server-1.2.2/client/node_modules/vscode-languageclient/lib/node/main.js:159:15)
    at closeHandler (/home/irisowner/.vscode-remote/extensions/intersystems.language-server-1.2.2/client/node_modules/vscode-languageclient/lib/common/client.js:2461:18)
    at CallbackList.invoke (/home/irisowner/.vscode-remote/extensions/intersystems.language-server-1.2.2/client/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
    at Emitter.fire (/home/irisowner/.vscode-remote/extensions/intersystems.language-server-1.2.2/client/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
    at closeHandler (/home/irisowner/.vscode-remote/extensions/intersystems.language-server-1.2.2/client/node_modules/vscode-jsonrpc/lib/common/connection.js:260:26)
    at CallbackList.invoke (/home/irisowner/.vscode-remote/extensions/intersystems.language-server-1.2.2/client/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
    at Emitter.fire (/home/irisowner/.vscode-remote/extensions/intersystems.language-server-1.2.2/client/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
    at IPCMessageReader.fireClose (/home/irisowner/.vscode-remote/extensions/intersystems.language-server-1.2.2/client/node_modules/vscode-jsonrpc/lib/common/messageReader.js:40:27)
    at ChildProcess.<anonymous> (/home/irisowner/.vscode-remote/extensions/intersystems.language-server-1.2.2/client/node_modules/vscode-jsonrpc/lib/node/main.js:33:45)
    at ChildProcess.emit (events.js:327:22)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:673:12)
[Error - 8:19:00 AM] Request textDocument/semanticTokens/full failed.
Error: Connection got disposed.
    at Object.dispose (/home/irisowner/.vscode-remote/extensions/intersystems.language-server-1.2.2/client/node_modules/vscode-jsonrpc/lib/common/connection.js:1061:27)
    at Object.dispose (/home/irisowner/.vscode-remote/extensions/intersystems.language-server-1.2.2/client/node_modules/vscode-languageclient/lib/common/client.js:73:35)
    at LanguageClient.handleConnectionClosed (/home/irisowner/.vscode-remote/extensions/intersystems.language-server-1.2.2/client/node_modules/vscode-languageclient/lib/common/client.js:2474:42)
    at LanguageClient.handleConnectionClosed (/home/irisowner/.vscode-remote/extensions/intersystems.language-server-1.2.2/client/node_modules/vscode-languageclient/lib/node/main.js:159:15)
    at closeHandler (/home/irisowner/.vscode-remote/extensions/intersystems.language-server-1.2.2/client/node_modules/vscode-languageclient/lib/common/client.js:2461:18)
    at CallbackList.invoke (/home/irisowner/.vscode-remote/extensions/intersystems.language-server-1.2.2/client/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
    at Emitter.fire (/home/irisowner/.vscode-remote/extensions/intersystems.language-server-1.2.2/client/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
    at closeHandler (/home/irisowner/.vscode-remote/extensions/intersystems.language-server-1.2.2/client/node_modules/vscode-jsonrpc/lib/common/connection.js:260:26)
    at CallbackList.invoke (/home/irisowner/.vscode-remote/extensions/intersystems.language-server-1.2.2/client/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
    at Emitter.fire (/home/irisowner/.vscode-remote/extensions/intersystems.language-server-1.2.2/client/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
    at IPCMessageReader.fireClose (/home/irisowner/.vscode-remote/extensions/intersystems.language-server-1.2.2/client/node_modules/vscode-jsonrpc/lib/common/messageReader.js:40:27)
    at ChildProcess.<anonymous> (/home/irisowner/.vscode-remote/extensions/intersystems.language-server-1.2.2/client/node_modules/vscode-jsonrpc/lib/node/main.js:33:45)
    at ChildProcess.emit (events.js:327:22)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:673:12)
[Error - 8:19:00 AM] Request textDocument/foldingRange failed.
Error: Connection got disposed.
    at Object.dispose (/home/irisowner/.vscode-remote/extensions/intersystems.language-server-1.2.2/client/node_modules/vscode-jsonrpc/lib/common/connection.js:1061:27)
    at Object.dispose (/home/irisowner/.vscode-remote/extensions/intersystems.language-server-1.2.2/client/node_modules/vscode-languageclient/lib/common/client.js:73:35)
    at LanguageClient.handleConnectionClosed (/home/irisowner/.vscode-remote/extensions/intersystems.language-server-1.2.2/client/node_modules/vscode-languageclient/lib/common/client.js:2474:42)
    at LanguageClient.handleConnectionClosed (/home/irisowner/.vscode-remote/extensions/intersystems.language-server-1.2.2/client/node_modules/vscode-languageclient/lib/node/main.js:159:15)
    at closeHandler (/home/irisowner/.vscode-remote/extensions/intersystems.language-server-1.2.2/client/node_modules/vscode-languageclient/lib/common/client.js:2461:18)
    at CallbackList.invoke (/home/irisowner/.vscode-remote/extensions/intersystems.language-server-1.2.2/client/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
    at Emitter.fire (/home/irisowner/.vscode-remote/extensions/intersystems.language-server-1.2.2/client/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
    at closeHandler (/home/irisowner/.vscode-remote/extensions/intersystems.language-server-1.2.2/client/node_modules/vscode-jsonrpc/lib/common/connection.js:260:26)
    at CallbackList.invoke (/home/irisowner/.vscode-remote/extensions/intersystems.language-server-1.2.2/client/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
    at Emitter.fire (/home/irisowner/.vscode-remote/extensions/intersystems.language-server-1.2.2/client/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
    at IPCMessageReader.fireClose (/home/irisowner/.vscode-remote/extensions/intersystems.language-server-1.2.2/client/node_modules/vscode-jsonrpc/lib/common/messageReader.js:40:27)
    at ChildProcess.<anonymous> (/home/irisowner/.vscode-remote/extensions/intersystems.language-server-1.2.2/client/node_modules/vscode-jsonrpc/lib/node/main.js:33:45)
    at ChildProcess.emit (events.js:327:22)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:673:12)
node: malloc.c:2401: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
[Info  - 8:19:00 AM] Connection to server got closed. Server will restart.
node: malloc.c:2401: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
[Info  - 8:19:01 AM] Connection to server got closed. Server will restart.
node: malloc.c:2401: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
[Info  - 8:19:01 AM] Connection to server got closed. Server will restart.
node: malloc.c:2401: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
[Error - 8:19:02 AM] Connection to server got closed. Server will not be restarted.

```

**Comment by isc-AndrewCheshire** [comment]
@daimor I don't know whether this problem is due to the shared libraries in our extension but it may well be - I looked through the Codespaces documentation and it seems that shared libraries in extensions need special handling for Codespaces: https://code.visualstudio.com/api/advanced-topics/remote-extensions#using-native-node.js-modules
