### ISSUE TITLE
Language Server REST requests do not use CA certs from OS cert store

### ISSUE THREAD

**Issue by CraigRegester** [intersystems/language-server#219]
Issue Type: <b>Bug</b>

Our IRIS for Health test instance uses a certificate signed by our organizational CA (i.e., not trusted on the big wide world web.) When we try to hover over the methods/etc to get help text, an error is logged similar to the one below... This happens with isfs or without.

If I use REST Client extension humao.rest-client to test the APIs InterSystems Language Server is calling, they work just fine. So seems like InterSystems Language Server isn't respecting the locally trusted certificate store? Our UCR instance that does have a globally trusted CA-backed cert does not exhibit this issue.

Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket._finishInit (_tls_wrap.js:932:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12) {
  code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY',

Extension version: 1.2.9
VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.17763
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E7-8870 v3 @ 2.10GHz (8 x 2095)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|24.00GB (11.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|
</details>

**Comment by isc-bsaviano** [comment]
@CraigRegester Does the Server Manager extension (InterSystems Tools view) work for that instance? It uses the same npm module to make the REST requests.

**Comment by CraigRegester** [comment]
`Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket._finishInit (_tls_wrap.js:932:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12) {
  code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'User-Agent': 'axios/0.24.0',
      'Content-Length': 109
    },
    method: 'post',
    url: 'https://iris-esb.internal-domain.org:443/api/atelier/v4/OURNAMESPACE/action/query',
    data: '{"query":"SELECT Description FROM %Dictionary.CompiledClass WHERE Name = ?","parameters":["%Library.Status"]}',
    withCredentials: true,
    jar: CookieJar {
      rejectPublicSuffixes: true,
      enableLooseMode: false,
      allowSpecialUseDomain: false,
      store: { idx: {} },
      prefixSecurity: 'silent',
      _cloneSync: [Function (anonymous)],
      _importCookiesSync: [Function (anonymous)],
      getCookiesSync: [Function (anonymous)],
      getCookieStringSync: [Function (anonymous)],
      getSetCookieStringsSync: [Function (anonymous)],
      removeAllCookiesSync: [Function (anonymous)],
      setCookieSync: [Function (anonymous)],
      serializeSync: [Function (anonymous)]
    },
    httpAgent: CookieAgent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 80,
      protocol: 'http:',
      options: [Object],
      requests: {},
      sockets: {},
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'fifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 0,
      jar: [CookieJar],
      [Symbol(kCapture)]: false
    },
    httpsAgent: CookieAgent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object],
      requests: {},
      sockets: [Object],
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'fifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      jar: [CookieJar],
      [Symbol(kCapture)]: false
    }
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'https:',
      path: '/api/atelier/v4/OURNAMESPACE/action/query',
      method: 'POST',
      headers: [Object],
      agent: [CookieAgent],
      agents: [Object],
      auth: undefined,
      hostname: 'iris-esb.internal-domain.org',
      port: '443',
      nativeProtocols: [Object],
      pathname: '/api/atelier/v4/OURNAMESPACE/action/query'
    },
    _ended: false,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 109,
    _requestBodyBuffers: [ [Object] ],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: false,
      _headerSent: true,
      socket: [TLSSocket],
      _header: 'POST /api/atelier/v4/OURNAMESPACE/action/query HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'User-Agent: axios/0.24.0\r\n' +
        'Content-Length: 109\r\n' +
        'Host: iris-esb.internal-domain.org\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [CookieAgent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/api/atelier/v4/OURNAMESPACE/action/query',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'iris-esb.internal-domain.org',
      protocol: 'https:',
      _redirectable: [Circular *1],
      emit: [Function (anonymous)],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'https://iris-esb.internal-domain.org:443/api/atelier/v4/OURNAMESPACE/action/query',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
`

Full error logged to the InterSystems Language Server output window... I had to sanitize a little bit but otherwise as is....

**Comment by isc-bsaviano** [comment]
@CraigRegester Thanks for the extra info. I'll see what I can find out

**Comment by isc-bsaviano** [comment]
@CraigRegester The issue is that VS Code itself loads the host OS's CA cert store when it starts up, but since the LS runs in it's own process it doesn't have access to those loaded certs. I will ask the VS Code team if there's a way to have the LS inherit VS Code's http Agent.

**Comment by CraigRegester** [comment]
Makes sense. There are a few extensions out there that supposedly make the local OS truststore available to other extensions - one is win-ca-cert I believe. 

I tinkered with it last week but it didn't help Language Server extension. Maybe the code within win-ca-cert however will help point in the right direction on how to implement access to the local CA store.

**Comment by isc-bsaviano** [comment]
@CraigRegester After talking with the VS Code team (https://github.com/microsoft/vscode/issues/145559) I will make my REST requests on the client instead of in the Language Server process so it can take advantage of VS Code's auto-loading of the CA certs. I'm currently working on a bunch of stuff for LS v2 so this will be included in that when it comes out.

**Comment by CraigRegester** [comment]
Seeing this after upgrading the extension

```
(node:23112) UnhandledPromiseRejectionWarning: Error: Request intersystems/server/makeRESTRequest failed with message: **Cannot read property 'data' of undefined**
    at c:\Users\142990\.vscode\extensions\intersystems.language-server-2.0.0\server\out\server.js:2:708402
    at c:\Users\142990\.vscode\extensions\intersystems.language-server-2.0.0\server\out\server.js:2:708696
    at Immediate.<anonymous> (c:\Users\142990\.vscode\extensions\intersystems.language-server-2.0.0\server\out\server.js:2:709061)
    at processImmediate (internal/timers.js:461:21)
(Use `Code --trace-warnings ...` to show where the warning was created)
(node:23112) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:23112) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Error - 1:27:57 PM] Request textDocument/hover failed.
  Message: Request intersystems/server/makeRESTRequest failed with message: Cannot read property 'data' of undefined
  Code: -32603 
[Error - 1:28:02 PM] Request textDocument/hover failed.
  Message: Request intersystems/server/makeRESTRequest failed with message: Cannot read property 'data' of undefined
  Code: -32603 
[Error - 1:28:04 PM] Request textDocument/hover failed.
  Message: Request intersystems/server/makeRESTRequest failed with message: Cannot read property 'data' of undefined
  Code: -32603 
[Error - 1:28:49 PM] Request textDocument/hover failed.
  Message: Request intersystems/server/makeRESTRequest failed with message: Cannot read property 'data' of undefined
  Code: -32603 
```

**Comment by isc-bsaviano** [comment]
@CraigRegester What platform are you on and what operation did you try to perform?

**Comment by CraigRegester** [comment]
Windows 10 x64 Professional - And all I did was load up my workspace and hover over a method to try and see the help text

**Comment by CraigRegester** [comment]
Tried again to piece it out a bit (the Code --trace-warnings didn't help at all)

The first block up to the 1st 'Request textDocument/hover failed ' was caused by loading up a class.... so maybe the initial call to the language server to get all the metadata.

All the individual textDocument/hover fialed is when I'm just moving my mouse around the class and it hits a method name (so it's trying to retrieve the help text on the method definition I presume)

**Comment by isc-bsaviano** [comment]
@CraigRegester Thanks for the info. I'm pretty sure I identified the bug, I will send you a beta vsix for windows with a fix when I have it.

**Comment by isc-bsaviano** [comment]
@CraigRegester I opened #220 and posted a beta vsix there

**Comment by isc-bsaviano** [comment]
@CraigRegester

Please try this vsix. I tested it with an HTTPS IRIS and it looks good to me.

[language-server-win32-x64-2.0.1-beta.2.vsix.zip](https://github.com/intersystems/language-server/files/8383469/language-server-win32-x64-2.0.1-beta.2.vsix.zip)

**Comment by CraigRegester** [comment]
Definitely better - I can hover over classes now and see definition... but the Go to Definition still isn't working (on UCR at least - gonna test on IRIS for Health next)

**Comment by CraigRegester** [comment]
![image](https://user-images.githubusercontent.com/65192819/160915438-558b2dea-3def-42d8-9494-0fec8ef2a8ff.png)

Same in IRIS for Health. Screenshot shows I can hover over %Net.HttpRequest but right-clicking and selecting Go to Definition... no dice.

**Comment by isc-bsaviano** [comment]
This is really odd. It looks like the cookies aren't being sent to the server when using HTTPS so the definition fails with a 401.

**Comment by CraigRegester** [comment]
> This is really odd. It looks like the cookies aren't being sent to the server when using HTTPS so the definition fails with a 401. 

Or maybe I need to adjust the atelier web app to not tightly scope cookies and/or permit cookies? Not sure. Responding from my phone so can't look but will try a couple different tweaks on the webapp to see if it helps.

**Comment by isc-bsaviano** [comment]
@CraigRegester I appreciate your help. The reason you're seeing 2 requests is that the LS always tries to authenticate using cookies first, but if that fails with a 401, it tries again with Basic auth. However, there's a bug that I'm working on where the cookies don't get stored for HTTPS, so the LS makes both request every time.

**Comment by CraigRegester** [comment]
Yeah I read through the typescript a bit after that post to try and look for any differences based on my experience working with similar tools but nothing obvious jumped out. :( No worries, happy to help - vested interest as I have a couple new-to-ISC developers and having the help text not showing up has been like them learning with one arm tied behind their back so happy to push through it with you!

Fyi, I also have an M1 MBP and I think issue #138 is similar/related to what we're seeing here now since the 2.0.0 release. I was seeing it last night as well when I was troubleshooting (not with python specifically but just in general - the hover overs, etc.)

So happy to test any beta of an extension for that architecture as well as you work through these. I obviously couldn't try beta 2 on the M1 Mac but happy to do so if you can produce one.

**Comment by isc-bsaviano** [comment]
@CraigRegester Can you try this vsix? The cookies issue looks fixed to me.

[language-server-win32-x64-2.0.1-beta.3.vsix.zip](https://github.com/intersystems/language-server/files/8390209/language-server-win32-x64-2.0.1-beta.3.vsix.zip)

**Comment by isc-bsaviano** [comment]
@CraigRegester That's great! It would super helpful if you could check your log for a LoginFailure, or use the HTTP Trace to see if the cookies are passed correctly. If either of those look good then I will consider this resolved and release 2.0.1

**Comment by CraigRegester** [comment]
Just clear the audit log in my dev env and retested - no LoginFailure events, just Logins - working well even with the delegated SSO setup UCR 2021.2 uses. Awesome work, ty!

**Comment by isc-bsaviano** [comment]
@DodgeDeBoulet @CraigRegester I just published 2.0.1. Thanks for all your help!

**Comment by DodgeDeBoulet** [comment]
Sooo .... I was seeing some weird indenting behavior and thought I had a problem with ObjectScript v1.4.4 Extension. I installed the pre-release version v1.5.2022022801 and immediately saw the _exact same behavior_ from the **Language Server** v2.0.1 that I reported for 2.0.0 in the other issue. Reverting to ObjectScript 1.4.4 made it go away (but the indenting oddity returned).

If this isn't the right avenue for reporting this, let me know ...

**Comment by isc-bsaviano** [comment]
@DodgeDeBoulet The pre-release version of the main extension is intended to be used alongside the pre-release version of the server manager extension. The only difference between those versions and the regular ones is that they use a new VS Code Authentication API for storing passwords securely. The pre-release extensions are not equal to the beta versions found on GitHub, that have the proposed API enabled. I'm not sure what you mean by "weird indenting behavior" but it's possible that the main extension is causing it. If you post an issue to that repo describing it I can take a look.
