### ISSUE TITLE
Support Windows ARM

### ISSUE THREAD

**Issue by mvhenderson** [intersystems/language-server#258]
Windows 11 ARM is not supported as noted [here](https://github.com/intersystems/language-server/issues/138#issuecomment-1419702300).  For those of us with Apple Silicon the only way to do HealthShare development (UCR and CV) is using a Win11 ARM virtual machine since there are no macOS ARM kits or any HS docker images available on the WRC distribution page. 

For now using Studio is an acceptable workaround but it would be nice for out-of-the-box VS Code support on Win11 ARM.  I'd be even happier with a HS macOS arm kit or docker HS linux arm image to get rid of the need for the windows VM all together.

**Comment by isc-bsaviano** [comment]
@mvhenderson I will see what I can do about getting a Windows ARM build. You can use the other 2 extensions on Windows ARM if you don't want to use Studio.

**Comment by isc-bsaviano** [comment]
@mvhenderson Attached is a zipped Windows ARM vsix. Can you try this out and let me know if it works for you? I don't have a windows arm machine or VM handy.

[language-server-win32-arm64-2.3.2-SNAPSHOT.vsix.zip](https://github.com/intersystems/language-server/files/10924997/language-server-win32-arm64-2.3.2-SNAPSHOT.vsix.zip)

**Comment by mvhenderson** [comment]
Did not load - let me know if there is anything else I can try

System (Parallels Virtual Machine)
```
Processor	Apple Silicon   3.20 GHz  (4 processors)
System type	64-bit operating system, ARM-based processor
Edition	        Windows 11 Enterprise
Version	        22H2
OS build        22621.1265
```

LS output channel (sans a massive webpack JS dump):
```
Error: node-loader:
Error: c:\Users\mike\.vscode\extensions\intersystems.language-server-2.3.2-SNAPSHOT\server\out\f48eafa168ffa6afdd30f707d9b40be7.node is not a valid Win32 application.

c:\Users\mike\.vscode\extensions\intersystems.language-server-2.3.2-SNAPSHOT\server\out\f48eafa168ffa6afdd30f707d9b40be7.node
    at 8534 (c:\Users\mike\.vscode\extensions\intersystems.language-server-2.3.2-SNAPSHOT\server\out\server.js:2:161)
    at __webpack_require__ (c:\Users\mike\.vscode\extensions\intersystems.language-server-2.3.2-SNAPSHOT\server\out\server.js:2:1129951)
    at 2812 (c:\Users\mike\.vscode\extensions\intersystems.language-server-2.3.2-SNAPSHOT\server\out\server.js:2:336)
    at __webpack_require__ (c:\Users\mike\.vscode\extensions\intersystems.language-server-2.3.2-SNAPSHOT\server\out\server.js:2:1129951)
    at 2108 (c:\Users\mike\.vscode\extensions\intersystems.language-server-2.3.2-SNAPSHOT\server\out\server.js:2:165103)
    at __webpack_require__ (c:\Users\mike\.vscode\extensions\intersystems.language-server-2.3.2-SNAPSHOT\server\out\server.js:2:1129951)
    at 2697 (c:\Users\mike\.vscode\extensions\intersystems.language-server-2.3.2-SNAPSHOT\server\out\server.js:2:185434)
    at __webpack_require__ (c:\Users\mike\.vscode\extensions\intersystems.language-server-2.3.2-SNAPSHOT\server\out\server.js:2:1129951)
    at c:\Users\mike\.vscode\extensions\intersystems.language-server-2.3.2-SNAPSHOT\server\out\server.js:2:1130551
    at Object.<anonymous> (c:\Users\mike\.vscode\extensions\intersystems.language-server-2.3.2-SNAPSHOT\server\out\server.js:2:1130802)
[Error - 10:01:26 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:01:26 AM] The InterSystems Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 10:01:26 AM] InterSystems Language Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:01:26 AM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
```

**Comment by isc-bsaviano** [comment]
@mvhenderson Thanks for checking, I will pass your error along to the team that handles the parser build infrastructure.

**Comment by isc-bsaviano** [comment]
@mvhenderson After discussing this with product management, we have decided that this isn't worth pursuing at this time. Submitting a WRC asking for a HS macOS arm kit or docker HS linux arm image is a better solution.

**Comment by isc-bsaviano** [comment]
I recently got access to a Windows Arm laptop, so I'm going to revisit this issue.
